"""added pending_plan_id in subscription

Revision ID: 072100c2a96d
Revises: feb4224c5daf
Create Date: 2026-06-04 03:23:28.117804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072100c2a96d'
down_revision: Union[str, Sequence[str], None] = 'feb4224c5daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('pending_plan_id', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('pending_change_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'pending_change_type')
    op.drop_column('subscriptions', 'pending_plan_id')
    # ### end Alembic commands ###
