"""updated is_Deleted name in user

Revision ID: 0da08909d8a3
Revises: 924d5fedd31b
Create Date: 2026-06-01 06:24:26.765743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da08909d8a3'
down_revision: Union[str, Sequence[str], None] = '924d5fedd31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('users', 'isdeleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isdeleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
