"""added unique on name in plans

Revision ID: 375c53c36eb2
Revises: ea176177e694
Create Date: 2026-05-31 15:07:51.735034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375c53c36eb2'
down_revision: Union[str, Sequence[str], None] = 'ea176177e694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'plans', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='unique')
    # ### end Alembic commands ###
