"""default value to cancel_at col in subscription

Revision ID: 92d8f8f32b31
Revises: c9d1780c88f0
Create Date: 2026-06-03 07:08:53.333953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d8f8f32b31'
down_revision: Union[str, Sequence[str], None] = 'c9d1780c88f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
