"""added isdeleted and isActive column in user table

Revision ID: 9b67bfba4e9c
Revises: 41d0c72c1f57
Create Date: 2026-05-29 16:21:27.143906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b67bfba4e9c'
down_revision: Union[str, Sequence[str], None] = '41d0c72c1f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isDeleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('isActive', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isActive')
    op.drop_column('users', 'isDeleted')
    # ### end Alembic commands ###
