"""added device_id in user_device table

Revision ID: ba065c715a57
Revises: 8bcf7e640083
Create Date: 2026-06-04 11:53:12.808581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba065c715a57'
down_revision: Union[str, Sequence[str], None] = '8bcf7e640083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_devices', sa.Column('device_id', sa.String(length=255), nullable=False))
    op.add_column('user_devices', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_devices', 'is_active')
    op.drop_column('user_devices', 'device_id')
    # ### end Alembic commands ###
