"""updated columns of tables

Revision ID: e4856eda7506
Revises: d3daaea769a7
Create Date: 2026-05-31 14:23:20.110349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4856eda7506'
down_revision: Union[str, Sequence[str], None] = 'd3daaea769a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_attachments_task_id'), 'task_attachments', ['task_id'], unique=False)
    op.drop_index(op.f('ix_taskAttachments_task_id'), table_name='taskAttachments')
    op.drop_table('taskAttachments')
    op.add_column('plans', sa.Column('striperice_id', sa.String(length=255), nullable=False))
    op.add_column('plans', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('max_tasks', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('max_users', sa.Integer(), nullable=False))
    op.drop_column('plans', 'isActive')
    op.drop_column('plans', 'maxUsers')
    op.drop_column('plans', 'stripe_price_id')
    op.drop_column('plans', 'maxTasks')
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('users', 'isActive')
    op.drop_column('users', 'isDeleted')
    op.add_column('workspaces', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('workspaces', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('workspaces', 'isdelete')
    op.drop_column('workspaces', 'isActive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('isdelete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('workspaces', 'is_active')
    op.drop_column('workspaces', 'is_deleted')
    op.add_column('users', sa.Column('isDeleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_deleted')
    op.add_column('plans', sa.Column('maxTasks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('stripe_price_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('maxUsers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('plans', 'max_users')
    op.drop_column('plans', 'max_tasks')
    op.drop_column('plans', 'is_active')
    op.drop_column('plans', 'striperice_id')
    op.create_table('taskAttachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('taskAttachments_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('taskAttachments_uploaded_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('taskAttachments_pkey'))
    )
    op.create_index(op.f('ix_taskAttachments_task_id'), 'taskAttachments', ['task_id'], unique=False)
    op.drop_index(op.f('ix_task_attachments_task_id'), table_name='task_attachments')
    op.drop_table('task_attachments')
    # ### end Alembic commands ###
