"""column name stripe_price_id updated

Revision ID: ea176177e694
Revises: e4856eda7506
Create Date: 2026-05-31 15:03:03.379556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea176177e694'
down_revision: Union[str, Sequence[str], None] = 'e4856eda7506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('stripe_price_id', sa.String(length=255), nullable=False))
    op.drop_column('plans', 'striperice_id')
    op.add_column('users', sa.Column('isdeleted', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'isdeleted')
    op.add_column('plans', sa.Column('striperice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('plans', 'stripe_price_id')
    # ### end Alembic commands ###
