"""content_type in attachment

Revision ID: eeb41d6fe46e
Revises: c1e3b3848c14
Create Date: 2026-06-01 16:54:46.991732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb41d6fe46e'
down_revision: Union[str, Sequence[str], None] = 'c1e3b3848c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_attachments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('task_attachments', sa.Column('content_type', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_attachments', 'content_type')
    op.drop_column('task_attachments', 'is_deleted')
    # ### end Alembic commands ###
